SET(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_SYSROOT $ENV{SYSROOT})

SET(CMAKE_C_COMPILER i686-pc-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER i686-pc-linux-gnu-g++)
SET(CMAKE_FIND_ROOT_PATH $ENV{SYSROOT})

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

#set(CMAKE_CXX_FLAGS "-Wl,--sysroot=~/sysroot --sysroot=~/sysroot -Wl,-rpath,~/sysroot/opt/gira/lib,-rpath,~/sysroot/usr/lib")
